import java.io.*;
import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.Map;
import java_cup.runtime.Symbol;

public class Main {

    // Map to store token ID -> Name (e.g., 2 -> "INT")
    private static Map<Integer, String> symbolNames = new HashMap<>();

    public static void main(String[] args) {
        // 1. Check arguments
        if (args.length == 0) {
            System.err.println("Uso incorrecto. Ejecutar: java Main <archivo_fuente>");
            System.exit(1);
        }

        String fileName = args[0];
        String outputFileName = "salida.txt";
        
        // Load symbol names from the generated 'sym' class using Reflection
        loadSymbolNames();

        System.out.println("Iniciando análisis léxico...");
        System.out.println("Entrada: " + fileName);
        System.out.println("Salida: " + outputFileName);

        try (FileReader reader = new FileReader(fileName);
             PrintWriter writer = new PrintWriter(new FileWriter(outputFileName))) {

            // 2. Initialize Lexer
            // LexerProyUno is the class generated by JFlex from jflex.flex
            LexerProyUno lexer = new LexerProyUno(reader);

            // 3. Loop through tokens
            while (true) {
                Symbol token = lexer.next_token();

                // sym.EOF (usually 0) indicates end of file
                if (token.sym == sym.EOF) {
                    writer.println("EOF (Fin de archivo)");
                    break;
                }

                // Get string representation of the token type
                String tokenName = getSymbolName(token.sym);
                
                // Get the value (lexeme or Object value if parsed)
                // Lexer returns Symbol(type, line, col, value) or Symbol(type, line, col)
                // token.value usually holds the parsed value (e.g. integer 15)
                // But for pure lexer output, we might want the original text.
                // JFlex's yytext() isn't directly exposed unless we add a method to the lexer
                // or assume token.value holds it. 
                // Based on jflex.flex: 
                // symbol(sym.INTEGER_LITERAL, Integer.parseInt(yytext())) -> value is Integer
                // symbol(sym.NAVIDAD) -> value is null (or undefined)
                
                String valueStr = "";
                if (token.value != null) {
                    valueStr = " -> " + token.value.toString();
                }

                // Write to output file: "TOKEN_NAME -> Value"
                // Example: INTEGER_LITERAL -> 123
                //          NAVIDAD -> 
                writer.println(tokenName + valueStr);
            }

            System.out.println("Análisis completado exitosamente.");
            System.out.println("Tokens guardados en: " + outputFileName);

        } catch (FileNotFoundException e) {
            System.err.println("Error: Archivo no encontrado - " + fileName);
        } catch (Exception e) {
            System.err.println("Error durante la ejecución: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * Loads public static final int fields from the 'sym' class to allow printing "PLUS" instead of "5".
     */
    private static void loadSymbolNames() {
        try {
            // Get all fields from the sym class
            Field[] fields = sym.class.getFields();
            for (Field field : fields) {
                // We only care about static final int fields
                if (field.getType() == int.class) {
                    int value = field.getInt(null);
                    String name = field.getName();
                    symbolNames.put(value, name);
                }
            }
        } catch (Exception e) {
            System.err.println("Advertencia: No se pudieron cargar los nombres de los símbolos de la clase 'sym'.");
            // Fallback: we will just print the integer ID if this fails.
        }
    }

    private static String getSymbolName(int id) {
        return symbolNames.getOrDefault(id, "SYM_" + id);
    }
}
